/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GrowthMeasurementView {
    id: bigint;
    heightCm?: number;
    date: string;
    dependentId: bigint;
    recordedAt: bigint;
    weightKg?: number;
}
export interface CustomMilestone {
    key: string;
    memberId: bigint;
    name: string;
    category: string;
    familyId: bigint;
}
export interface MyPermissions {
    canAddMemories: boolean;
    canViewMeasurementsAndMilestones: boolean;
    canAddMeasurementsAndMilestones: boolean;
    isOwner: boolean;
}
export interface Family {
    id: bigint;
    owner: Principal;
    name: string;
    createdAt: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface LikeInfo {
    count: bigint;
    likedByMe: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FamilyMemberView {
    permissions: Permissions;
    principal: Principal;
    relationship: Relationship;
    displayName: string;
    joinedAt: bigint;
    isOwner: boolean;
}
export interface Profile {
    photoBlob?: ExternalBlob;
    name: string;
}
export interface Permissions {
    canAddMemories: boolean;
    canViewMeasurementsAndMilestones: boolean;
    canAddMeasurementsAndMilestones: boolean;
}
export interface Dependent {
    id: bigint;
    sex?: PetSex;
    photoBlob?: ExternalBlob;
    dateOfBirth?: string;
    kind: MemberKind;
    name: string;
    petType?: string;
    breed?: string;
    adoptionDate?: string;
    familyId: bigint;
}
export interface CommentView {
    id: bigint;
    createdAt: bigint;
    text: string;
    authorName: string;
    author: Principal;
    memoryId: bigint;
    canDelete: boolean;
}
export interface MemoryView {
    id: bigint;
    taggedMemberIds: Array<bigint>;
    date: string;
    createdAt: bigint;
    authorName: string;
    author: Principal;
    mediaBlobs: Array<ExternalBlob>;
    caption?: string;
    milestoneKey?: string;
    isAuthor: boolean;
    milestoneMemberId?: bigint;
    familyId: bigint;
    authorPhotoBlob?: ExternalBlob;
    mediaTypes: Array<string>;
}
export interface DaySummary {
    memoryCount: bigint;
    date: string;
    previewCaption?: string;
    previewBlob?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PaginatedMemories {
    hasMore: boolean;
    memories: Array<MemoryView>;
    nextCursor?: bigint;
}
export enum MemberKind {
    pet = "pet",
    child = "child"
}
export enum PetSex {
    female = "female",
    male = "male",
    unknown_ = "unknown"
}
export enum Relationship {
    grandmother = "grandmother",
    grandfather = "grandfather",
    other = "other",
    aunt = "aunt",
    uncle = "uncle",
    friend = "friend",
    mother = "mother",
    cousin = "cousin",
    father = "father"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addComment(familyId: bigint, memoryId: bigint, text: string): Promise<bigint>;
    addDependent(familyId: bigint, kind: MemberKind, name: string, dateOfBirth: string | null, petType: string | null, breed: string | null, sex: PetSex | null, adoptionDate: string | null, photoBlob: ExternalBlob | null): Promise<bigint>;
    addGrowthMeasurement(familyId: bigint, dependentId: bigint, date: string, heightCm: number | null, weightKg: number | null): Promise<bigint>;
    createCustomMilestone(familyId: bigint, memberId: bigint, name: string, category: string | null): Promise<string>;
    createFamily(name: string): Promise<bigint>;
    createMemory(familyId: bigint, date: string, caption: string | null, mediaBlobs: Array<ExternalBlob>, mediaTypes: Array<string>, taggedMemberIds: Array<bigint>, milestoneKey: string | null, milestoneMemberId: bigint | null): Promise<bigint>;
    deleteComment(familyId: bigint, commentId: bigint, memoryId: bigint): Promise<void>;
    deleteCustomMilestone(familyId: bigint, memberId: bigint, milestoneKey: string): Promise<void>;
    deleteFamily(familyId: bigint): Promise<void>;
    deleteGrowthMeasurement(familyId: bigint, measurementId: bigint): Promise<void>;
    deleteMemory(familyId: bigint, memoryId: bigint): Promise<void>;
    generateInviteCode(familyId: bigint): Promise<string>;
    getAchievedMilestoneKeys(familyId: bigint, memberId: bigint): Promise<Array<string>>;
    getComments(familyId: bigint, memoryId: bigint): Promise<Array<CommentView>>;
    getCustomMilestones(familyId: bigint, memberId: bigint): Promise<Array<CustomMilestone>>;
    getFamily(familyId: bigint): Promise<Family | null>;
    getFamilyDependents(familyId: bigint): Promise<Array<Dependent>>;
    getFamilyMembers(familyId: bigint): Promise<Array<FamilyMemberView>>;
    getFlashbacks(familyId: bigint, date: string): Promise<Array<MemoryView>>;
    getGrowthMeasurements(familyId: bigint, dependentId: bigint): Promise<Array<GrowthMeasurementView>>;
    getLikes(familyId: bigint, memoryId: bigint): Promise<LikeInfo>;
    getMediaMemories(familyId: bigint, cursor: bigint | null, limit: bigint, memberId: bigint | null): Promise<PaginatedMemories>;
    getMemberMomentCount(familyId: bigint, memberId: bigint): Promise<bigint>;
    getMemoriesByDate(familyId: bigint, date: string): Promise<Array<MemoryView>>;
    getMemoriesForMilestone(familyId: bigint, memberId: bigint, milestoneKey: string): Promise<Array<MemoryView>>;
    getMonthSummary(familyId: bigint, year: bigint, month: bigint, memberId: bigint | null): Promise<Array<DaySummary>>;
    getMyPermissions(familyId: bigint): Promise<MyPermissions>;
    getProfile(): Promise<Profile | null>;
    getRecentMemories(familyId: bigint, cursor: bigint | null, limit: bigint, memberId: bigint | null): Promise<PaginatedMemories>;
    getUserFamilies(): Promise<Array<Family>>;
    redeemInviteCode(code: string, relationship: Relationship): Promise<Family>;
    removeDependent(familyId: bigint, dependentId: bigint): Promise<void>;
    removeFamilyMember(familyId: bigint, member: Principal): Promise<void>;
    searchMemories(familyId: bigint, searchText: string): Promise<Array<MemoryView>>;
    setProfile(name: string, photoBlob: ExternalBlob | null): Promise<void>;
    toggleLike(familyId: bigint, memoryId: bigint): Promise<LikeInfo>;
    updateDependent(familyId: bigint, dependentId: bigint, name: string, dateOfBirth: string | null, petType: string | null, breed: string | null, sex: PetSex | null, adoptionDate: string | null, photoBlob: ExternalBlob | null): Promise<void>;
    updateMemberPermissions(familyId: bigint, member: Principal, permissions: Permissions): Promise<void>;
    updateMemberRelationship(familyId: bigint, member: Principal, relationship: Relationship): Promise<void>;
    updateMemory(familyId: bigint, memoryId: bigint, date: string, caption: string | null, mediaBlobs: Array<ExternalBlob>, mediaTypes: Array<string>, taggedMemberIds: Array<bigint>, milestoneKey: string | null, milestoneMemberId: bigint | null): Promise<void>;
}
import type { DaySummary as _DaySummary, Dependent as _Dependent, ExternalBlob as _ExternalBlob, Family as _Family, FamilyMemberView as _FamilyMemberView, GrowthMeasurementView as _GrowthMeasurementView, MemberKind as _MemberKind, MemoryView as _MemoryView, PaginatedMemories as _PaginatedMemories, Permissions as _Permissions, PetSex as _PetSex, Profile as _Profile, Relationship as _Relationship, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2);
            return result;
        }
    }
    async addDependent(arg0: bigint, arg1: MemberKind, arg2: string, arg3: string | null, arg4: string | null, arg5: string | null, arg6: PetSex | null, arg7: string | null, arg8: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDependent(arg0, to_candid_MemberKind_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg7), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDependent(arg0, to_candid_MemberKind_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg7), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async addGrowthMeasurement(arg0: bigint, arg1: bigint, arg2: string, arg3: number | null, arg4: number | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGrowthMeasurement(arg0, arg1, arg2, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGrowthMeasurement(arg0, arg1, arg2, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createCustomMilestone(arg0: bigint, arg1: bigint, arg2: string, arg3: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomMilestone(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomMilestone(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createFamily(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFamily(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFamily(arg0);
            return result;
        }
    }
    async createMemory(arg0: bigint, arg1: string, arg2: string | null, arg3: Array<ExternalBlob>, arg4: Array<string>, arg5: Array<bigint>, arg6: string | null, arg7: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMemory(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_vec_n17(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMemory(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_vec_n17(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async deleteComment(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCustomMilestone(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomMilestone(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomMilestone(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteFamily(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFamily(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFamily(arg0);
            return result;
        }
    }
    async deleteGrowthMeasurement(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGrowthMeasurement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGrowthMeasurement(arg0, arg1);
            return result;
        }
    }
    async deleteMemory(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMemory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMemory(arg0, arg1);
            return result;
        }
    }
    async generateInviteCode(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode(arg0);
            return result;
        }
    }
    async getAchievedMilestoneKeys(arg0: bigint, arg1: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievedMilestoneKeys(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievedMilestoneKeys(arg0, arg1);
            return result;
        }
    }
    async getComments(arg0: bigint, arg1: bigint): Promise<Array<CommentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0, arg1);
            return result;
        }
    }
    async getCustomMilestones(arg0: bigint, arg1: bigint): Promise<Array<CustomMilestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomMilestones(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomMilestones(arg0, arg1);
            return result;
        }
    }
    async getFamily(arg0: bigint): Promise<Family | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamily(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamily(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFamilyDependents(arg0: bigint): Promise<Array<Dependent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyDependents(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyDependents(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFamilyMembers(arg0: bigint): Promise<Array<FamilyMemberView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyMembers(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyMembers(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlashbacks(arg0: bigint, arg1: string): Promise<Array<MemoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashbacks(arg0, arg1);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashbacks(arg0, arg1);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrowthMeasurements(arg0: bigint, arg1: bigint): Promise<Array<GrowthMeasurementView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrowthMeasurements(arg0, arg1);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrowthMeasurements(arg0, arg1);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikes(arg0: bigint, arg1: bigint): Promise<LikeInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikes(arg0, arg1);
            return result;
        }
    }
    async getMediaMemories(arg0: bigint, arg1: bigint | null, arg2: bigint, arg3: bigint | null): Promise<PaginatedMemories> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaMemories(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3));
                return from_candid_PaginatedMemories_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaMemories(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3));
            return from_candid_PaginatedMemories_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberMomentCount(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberMomentCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberMomentCount(arg0, arg1);
            return result;
        }
    }
    async getMemoriesByDate(arg0: bigint, arg1: string): Promise<Array<MemoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemoriesByDate(arg0, arg1);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemoriesByDate(arg0, arg1);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemoriesForMilestone(arg0: bigint, arg1: bigint, arg2: string): Promise<Array<MemoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemoriesForMilestone(arg0, arg1, arg2);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemoriesForMilestone(arg0, arg1, arg2);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthSummary(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint | null): Promise<Array<DaySummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthSummary(arg0, arg1, arg2, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthSummary(arg0, arg1, arg2, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPermissions(arg0: bigint): Promise<MyPermissions> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPermissions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPermissions(arg0);
            return result;
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentMemories(arg0: bigint, arg1: bigint | null, arg2: bigint, arg3: bigint | null): Promise<PaginatedMemories> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentMemories(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3));
                return from_candid_PaginatedMemories_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentMemories(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3));
            return from_candid_PaginatedMemories_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFamilies(): Promise<Array<Family>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFamilies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFamilies();
            return result;
        }
    }
    async redeemInviteCode(arg0: string, arg1: Relationship): Promise<Family> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemInviteCode(arg0, to_candid_Relationship_n52(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemInviteCode(arg0, to_candid_Relationship_n52(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async removeDependent(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDependent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDependent(arg0, arg1);
            return result;
        }
    }
    async removeFamilyMember(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFamilyMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFamilyMember(arg0, arg1);
            return result;
        }
    }
    async searchMemories(arg0: bigint, arg1: string): Promise<Array<MemoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMemories(arg0, arg1);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMemories(arg0, arg1);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProfile(arg0: string, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async toggleLike(arg0: bigint, arg1: bigint): Promise<LikeInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0, arg1);
            return result;
        }
    }
    async updateDependent(arg0: bigint, arg1: bigint, arg2: string, arg3: string | null, arg4: string | null, arg5: string | null, arg6: PetSex | null, arg7: string | null, arg8: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDependent(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg7), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDependent(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg7), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateMemberPermissions(arg0: bigint, arg1: Principal, arg2: Permissions): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberPermissions(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberPermissions(arg0, arg1, arg2);
            return result;
        }
    }
    async updateMemberRelationship(arg0: bigint, arg1: Principal, arg2: Relationship): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberRelationship(arg0, arg1, to_candid_Relationship_n52(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberRelationship(arg0, arg1, to_candid_Relationship_n52(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateMemory(arg0: bigint, arg1: bigint, arg2: string, arg3: string | null, arg4: Array<ExternalBlob>, arg5: Array<string>, arg6: Array<bigint>, arg7: string | null, arg8: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemory(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_vec_n17(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemory(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_vec_n17(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
}
async function from_candid_DaySummary_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DaySummary): Promise<DaySummary> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_Dependent_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dependent): Promise<Dependent> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FamilyMemberView_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FamilyMemberView): FamilyMemberView {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_GrowthMeasurementView_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GrowthMeasurementView): GrowthMeasurementView {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_MemberKind_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberKind): MemberKind {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_MemoryView_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemoryView): Promise<MemoryView> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_PaginatedMemories_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedMemories): Promise<PaginatedMemories> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_PetSex_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PetSex): PetSex {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_Profile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Promise<Profile> {
    return await from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Relationship_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Relationship): Relationship {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Family]): Family | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PetSex]): PetSex | null {
    return value.length === 0 ? null : from_candid_PetSex_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Promise<Profile | null> {
    return value.length === 0 ? null : await from_candid_Profile_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    sex: [] | [_PetSex];
    photoBlob: [] | [_ExternalBlob];
    dateOfBirth: [] | [string];
    kind: _MemberKind;
    name: string;
    petType: [] | [string];
    breed: [] | [string];
    adoptionDate: [] | [string];
    familyId: bigint;
}): Promise<{
    id: bigint;
    sex?: PetSex;
    photoBlob?: ExternalBlob;
    dateOfBirth?: string;
    kind: MemberKind;
    name: string;
    petType?: string;
    breed?: string;
    adoptionDate?: string;
    familyId: bigint;
}> {
    return {
        id: value.id,
        sex: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.sex)),
        photoBlob: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.photoBlob)),
        dateOfBirth: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.dateOfBirth)),
        kind: from_candid_MemberKind_n29(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        petType: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.petType)),
        breed: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.breed)),
        adoptionDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.adoptionDate)),
        familyId: value.familyId
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: _Permissions;
    principal: Principal;
    relationship: _Relationship;
    displayName: string;
    joinedAt: bigint;
    isOwner: boolean;
}): {
    permissions: Permissions;
    principal: Principal;
    relationship: Relationship;
    displayName: string;
    joinedAt: bigint;
    isOwner: boolean;
} {
    return {
        permissions: value.permissions,
        principal: value.principal,
        relationship: from_candid_Relationship_n34(_uploadFile, _downloadFile, value.relationship),
        displayName: value.displayName,
        joinedAt: value.joinedAt,
        isOwner: value.isOwner
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    taggedMemberIds: Array<bigint>;
    date: string;
    createdAt: bigint;
    authorName: string;
    author: Principal;
    mediaBlobs: Array<_ExternalBlob>;
    caption: [] | [string];
    milestoneKey: [] | [string];
    isAuthor: boolean;
    milestoneMemberId: [] | [bigint];
    familyId: bigint;
    authorPhotoBlob: [] | [_ExternalBlob];
    mediaTypes: Array<string>;
}): Promise<{
    id: bigint;
    taggedMemberIds: Array<bigint>;
    date: string;
    createdAt: bigint;
    authorName: string;
    author: Principal;
    mediaBlobs: Array<ExternalBlob>;
    caption?: string;
    milestoneKey?: string;
    isAuthor: boolean;
    milestoneMemberId?: bigint;
    familyId: bigint;
    authorPhotoBlob?: ExternalBlob;
    mediaTypes: Array<string>;
}> {
    return {
        id: value.id,
        taggedMemberIds: value.taggedMemberIds,
        date: value.date,
        createdAt: value.createdAt,
        authorName: value.authorName,
        author: value.author,
        mediaBlobs: await from_candid_vec_n39(_uploadFile, _downloadFile, value.mediaBlobs),
        caption: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.caption)),
        milestoneKey: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.milestoneKey)),
        isAuthor: value.isAuthor,
        milestoneMemberId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.milestoneMemberId)),
        familyId: value.familyId,
        authorPhotoBlob: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.authorPhotoBlob)),
        mediaTypes: value.mediaTypes
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    heightCm: [] | [number];
    date: string;
    dependentId: bigint;
    recordedAt: bigint;
    weightKg: [] | [number];
}): {
    id: bigint;
    heightCm?: number;
    date: string;
    dependentId: bigint;
    recordedAt: bigint;
    weightKg?: number;
} {
    return {
        id: value.id,
        heightCm: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.heightCm)),
        date: value.date,
        dependentId: value.dependentId,
        recordedAt: value.recordedAt,
        weightKg: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.weightKg))
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    memories: Array<_MemoryView>;
    nextCursor: [] | [bigint];
}): Promise<{
    hasMore: boolean;
    memories: Array<MemoryView>;
    nextCursor?: bigint;
}> {
    return {
        hasMore: value.hasMore,
        memories: await from_candid_vec_n36(_uploadFile, _downloadFile, value.memories),
        nextCursor: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextCursor))
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memoryCount: bigint;
    date: string;
    previewCaption: [] | [string];
    previewBlob: [] | [_ExternalBlob];
}): Promise<{
    memoryCount: bigint;
    date: string;
    previewCaption?: string;
    previewBlob?: ExternalBlob;
}> {
    return {
        memoryCount: value.memoryCount,
        date: value.date,
        previewCaption: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.previewCaption)),
        previewBlob: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.previewBlob))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photoBlob: [] | [_ExternalBlob];
    name: string;
}): Promise<{
    photoBlob?: ExternalBlob;
    name: string;
}> {
    return {
        photoBlob: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.photoBlob)),
        name: value.name
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
} | {
    unknown: null;
}): PetSex {
    return "female" in value ? PetSex.female : "male" in value ? PetSex.male : "unknown" in value ? PetSex.unknown : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pet: null;
} | {
    child: null;
}): MemberKind {
    return "pet" in value ? MemberKind.pet : "child" in value ? MemberKind.child : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grandmother: null;
} | {
    grandfather: null;
} | {
    other: null;
} | {
    aunt: null;
} | {
    uncle: null;
} | {
    friend: null;
} | {
    mother: null;
} | {
    cousin: null;
} | {
    father: null;
}): Relationship {
    return "grandmother" in value ? Relationship.grandmother : "grandfather" in value ? Relationship.grandfather : "other" in value ? Relationship.other : "aunt" in value ? Relationship.aunt : "uncle" in value ? Relationship.uncle : "friend" in value ? Relationship.friend : "mother" in value ? Relationship.mother : "cousin" in value ? Relationship.cousin : "father" in value ? Relationship.father : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Dependent>): Promise<Array<Dependent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Dependent_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FamilyMemberView>): Array<FamilyMemberView> {
    return value.map((x)=>from_candid_FamilyMemberView_n32(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemoryView>): Promise<Array<MemoryView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MemoryView_n37(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GrowthMeasurementView>): Array<GrowthMeasurementView> {
    return value.map((x)=>from_candid_GrowthMeasurementView_n41(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DaySummary>): Promise<Array<DaySummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DaySummary_n47(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MemberKind_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberKind): _MemberKind {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PetSex_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PetSex): _PetSex {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Relationship_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Relationship): _Relationship {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PetSex | null): [] | [_PetSex] {
    return value === null ? candid_none() : candid_some(to_candid_PetSex_n12(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PetSex): {
    female: null;
} | {
    male: null;
} | {
    unknown: null;
} {
    return value == PetSex.female ? {
        female: null
    } : value == PetSex.male ? {
        male: null
    } : value == PetSex.unknown ? {
        unknown_: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Relationship): {
    grandmother: null;
} | {
    grandfather: null;
} | {
    other: null;
} | {
    aunt: null;
} | {
    uncle: null;
} | {
    friend: null;
} | {
    mother: null;
} | {
    cousin: null;
} | {
    father: null;
} {
    return value == Relationship.grandmother ? {
        grandmother: null
    } : value == Relationship.grandfather ? {
        grandfather: null
    } : value == Relationship.other ? {
        other: null
    } : value == Relationship.aunt ? {
        aunt: null
    } : value == Relationship.uncle ? {
        uncle: null
    } : value == Relationship.friend ? {
        friend: null
    } : value == Relationship.mother ? {
        mother: null
    } : value == Relationship.cousin ? {
        cousin: null
    } : value == Relationship.father ? {
        father: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberKind): {
    pet: null;
} | {
    child: null;
} {
    return value == MemberKind.pet ? {
        pet: null
    } : value == MemberKind.child ? {
        child: null
    } : value;
}
async function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
